graph TD
  A[Broker]

  A --> B1[Topic: orders]
  A --> B2[Topic: payments]

  B1 --> C1[Partition 0]
  B2 --> C2[Partition 0]

  C1 --> D1[High Priority Queue]
  C1 --> D2[Low Priority Queue]
  C1 --> E1[Consumer Offsets Map]

  C2 --> D3[High Priority Queue]
  C2 --> D4[Low Priority Queue]
  C2 --> E2[Consumer Offsets Map]

  subgraph API Endpoints
    F1[POST /topic/:topic/publish]
    F2[GET /topic/:topic/peek]
    F3[GET /topic/:topic/consume]
    F4[GET /topics]
    F5[GET /topics/:topic/partitions]
  end

  F1 --> A
  F2 --> A
  F3 --> A
  F4 --> A
  F5 --> A
